version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = false
